---
- hosts: all
  become: yes
  user: vagrant
  tasks:
    - name: install packages
      yum: name={{ item }} state=installed
      with_items:
        - vim
        - tree

    - name: set timezone to Asia/Tokyo
      timezone:
        name: Asia/Tokyo

    - name: set locale
      lineinfile:
        dest: "/etc/locale.conf"
        regexp: '^LANG=".*"'
        line: 'LANG="ja_JP.utf8"'

    - name: Install required packages for docker
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: install docker repository
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: install dcoker
      yum:
        name: docker-ce
        state: installed

    - name: user into docker group
      user:
        name: vagrant
        groups:
          - vagrant
          - docker
      when: skip_user_in_group is not defined

    - name: get docker composer binary
      get_url:
        url: https://github.com/docker/compose/releases/download/1.17.0/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: a+x

    - name: enable service docker
      systemd:
        name: docker
        state: started
        enabled: True
